version: '2'
services: 
  kong-database:
    image: postgres
    container_name: kong-database
    restart: always
    volumes:
      - H:/kong/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
  kong-prepare:
    image: kong:latest
    container_name: kong-prepare
    environment: 
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations up
    links:
      - kong-database  
  kong-core:
    image: kong:latest
    container_name: kong-core
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    restart: always
    ports:
      - 8001:8001
      - 8443:8443
      - 8000:8000
      - 8444:8444
    links:
      - kong-database
    volumes:
      - H:/kong/kong.conf:/usr/local/kong/kong.conf
      - H:/kong/nginx-kong.conf:/usr/local/kong/nginx-kong.conf
  kong-ui:
    image: pgbi/kong-dashboard
    container_name: kong-ui
    restart: always
    links:
      - kong-core
    ports:
      - 8080:8080